// Turns the maps3d capture's terrain TIN into a 16-bit landscape heightmap.
//
//   node tools/maps3d-terrain.mjs <capture.glb> [--out out] [--res 4033]
//
// The capture is real surveyed elevation, which is the thing the traced
// geography never was. Everything else in this pipeline can be regenerated from
// it, but the landscape has to come first: it is the one asset Unreal cannot
// build from script, so it is the long pole, and every other command reads its
// sidecar to know where the world is.
//
// Two things about the source have to be got right or nothing else lines up.
//
// SCALE. The capture's horizontal axes are Web Mercator metres, not ground
// metres. At this latitude that is a factor of 1/cos(32.711 deg) = 1.1885, and
// the vertical axis is already true metres — so importing it as-is gives a city
// 19% too wide for its own building heights. Every horizontal figure read out
// of the glb is multiplied by cos(lat) on the way in.
//
// FRAME. The capture is 13.2 x 11.8 km. The landscape is deliberately larger,
// with the capture centred in it and a ring of generated terrain around the
// outside. That ring is the out-of-bounds zone: somewhere a player can walk
// into and die in, rather than an invisible wall at the edge of the real data.
// It is generated by continuing the elevation at the nearest point on the
// capture's edge, so the join is seamless by construction — ocean stays ocean,
// a mesa keeps climbing — and then drifting toward a backdrop profile.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { deflateSync } from 'node:zlib';

const args = process.argv.slice(2);
const src = args[0];
const arg = (n, d) => {
  const i = args.indexOf('--' + n);
  return i >= 0 && args[i + 1] ? args[i + 1] : d;
};
if (!src) {
  console.error('usage: node tools/maps3d-terrain.mjs <capture.glb> [--out DIR] [--res N]');
  process.exit(1);
}
const OUT = arg('out', 'out');
const RES = parseInt(arg('res', '4033'), 10);
/** Metres of out-of-bounds terrain on each side of the capture. */
const RING_M = parseFloat(arg('ring', '2000'));

mkdirSync(OUT, { recursive: true });

// ── Read the glb ────────────────────────────────────────────────────────────

const buf = readFileSync(src);
if (buf.readUInt32LE(0) !== 0x46546c67) throw new Error('not a glb');
const jsonLen = buf.readUInt32LE(12);
const gltf = JSON.parse(buf.subarray(20, 20 + jsonLen).toString('utf8'));
// The BIN chunk follows the JSON chunk, both 4-byte aligned.
let off = 20 + jsonLen;
const binLen = buf.readUInt32LE(off);
const BIN = buf.subarray(off + 8, off + 8 + binLen);

const COMPONENT = {
  5120: [Int8Array, 1], 5121: [Uint8Array, 1], 5122: [Int16Array, 2],
  5123: [Uint16Array, 2], 5125: [Uint32Array, 4], 5126: [Float32Array, 4],
};
const NUM = { SCALAR: 1, VEC2: 2, VEC3: 3, VEC4: 4, MAT4: 16 };

function readAccessor(i) {
  const a = gltf.accessors[i];
  const [Type, bytes] = COMPONENT[a.componentType];
  const n = NUM[a.type];
  const bv = gltf.bufferViews[a.bufferView];
  const base = (bv.byteOffset ?? 0) + (a.byteOffset ?? 0);
  const stride = bv.byteStride ?? 0;
  if (!stride || stride === bytes * n) {
    // Tightly packed. Copy so the typed array is aligned.
    const slice = BIN.subarray(base, base + a.count * n * bytes);
    return new Type(Uint8Array.from(slice).buffer);
  }
  const out = new Type(a.count * n);
  for (let e = 0; e < a.count; e++) {
    const o = base + e * stride;
    for (let c = 0; c < n; c++) {
      const b = Uint8Array.from(BIN.subarray(o + c * bytes, o + (c + 1) * bytes));
      out[e * n + c] = new Type(b.buffer)[0];
    }
  }
  return out;
}

const rootByName = {};
for (const i of gltf.scenes[gltf.scene ?? 0].nodes) {
  rootByName[gltf.nodes[i].name ?? String(i)] = i;
}
const tinIdx = rootByName.tinMesh;
if (tinIdx === undefined) throw new Error('no tinMesh node in this capture');

const tin = gltf.meshes[gltf.nodes[tinIdx].mesh];
console.log('tinMesh: %d primitive(s)', tin.primitives.length);

// ── Rasterise the TIN ───────────────────────────────────────────────────────
//
// Straight scanline fill per triangle with barycentric interpolation. About
// 100,000 triangles over a 4000-pixel raster; a proper sweep would be faster
// but this runs in seconds and is much easier to be sure of.

const sidecarJson = join(OUT, 'sandiego.json');

// Capture extent, in mesh (Mercator) units — measured, not assumed.
let mnX = Infinity; let mxX = -Infinity; let mnZ = Infinity; let mxZ = -Infinity;
let mnY = Infinity; let mxY = -Infinity;
const prims = [];
for (const p of tin.primitives) {
  const pos = readAccessor(p.attributes.POSITION);
  const idx = readAccessor(p.indices);
  prims.push({ pos, idx });
  for (let i = 0; i < pos.length; i += 3) {
    if (pos[i] < mnX) mnX = pos[i];
    if (pos[i] > mxX) mxX = pos[i];
    if (pos[i + 1] < mnY) mnY = pos[i + 1];
    if (pos[i + 1] > mxY) mxY = pos[i + 1];
    if (pos[i + 2] < mnZ) mnZ = pos[i + 2];
    if (pos[i + 2] > mxZ) mxZ = pos[i + 2];
  }
}
console.log(`capture mesh extent  X ${mnX.toFixed(1)}..${mxX.toFixed(1)}`
  + `  Z ${mnZ.toFixed(1)}..${mxZ.toFixed(1)}  Y ${mnY.toFixed(2)}..${mxY.toFixed(2)}`);

// Mercator -> true ground metres.
const meta = JSON.parse(readFileSync(src.replace(/\.glb$/i, '.maps3d.json'), 'utf8'));
const lat0 = meta.params.areaSelected.rectCenter[1];
const lon0 = meta.params.areaSelected.rectCenter[0];
const K = Math.cos((lat0 * Math.PI) / 180);
const playW = (mxX - mnX) * K;
const playH = (mxZ - mnZ) * K;
console.log('capture true ground  %s x %s m   (1 unit = %s m)',
  playW.toFixed(0), playH.toFixed(0), K.toFixed(5));

// The landscape frame: the capture plus a ring, made square so the heightmap is.
const frame = Math.max(playW, playH) + RING_M * 2;
console.log('landscape frame      %s x %s m  (ring %s m each side)',
  frame.toFixed(0), frame.toFixed(0), RING_M.toFixed(0));

const mPerSample = frame / (RES - 1);
const height = new Float32Array(RES * RES).fill(NaN);

// Mesh unit -> raster coordinate.
const cx = (mnX + mxX) / 2;
const cz = (mnZ + mxZ) / 2;
const toCol = (x) => (((x - cx) * K) / frame + 0.5) * (RES - 1);
const toRow = (z) => (((z - cz) * K) / frame + 0.5) * (RES - 1);

let tris = 0;
for (const { pos, idx } of prims) {
  for (let t = 0; t + 2 < idx.length; t += 3) {
    const a = idx[t] * 3; const b = idx[t + 1] * 3; const c = idx[t + 2] * 3;
    const ax = toCol(pos[a]); const ay = toRow(pos[a + 2]); const av = pos[a + 1];
    const bx = toCol(pos[b]); const by = toRow(pos[b + 2]); const bv = pos[b + 1];
    const cx2 = toCol(pos[c]); const cy = toRow(pos[c + 2]); const cv = pos[c + 1];

    const r0 = Math.max(0, Math.floor(Math.min(ay, by, cy)));
    const r1 = Math.min(RES - 1, Math.ceil(Math.max(ay, by, cy)));
    const c0 = Math.max(0, Math.floor(Math.min(ax, bx, cx2)));
    const c1 = Math.min(RES - 1, Math.ceil(Math.max(ax, bx, cx2)));
    const den = (by - cy) * (ax - cx2) + (cx2 - bx) * (ay - cy);
    if (Math.abs(den) < 1e-12) continue;

    for (let r = r0; r <= r1; r++) {
      for (let col = c0; col <= c1; col++) {
        const w0 = ((by - cy) * (col - cx2) + (cx2 - bx) * (r - cy)) / den;
        const w1 = ((cy - ay) * (col - cx2) + (ax - cx2) * (r - cy)) / den;
        const w2 = 1 - w0 - w1;
        // A small negative tolerance closes the hairline gaps between
        // triangles that exact edge tests leave behind.
        if (w0 < -0.002 || w1 < -0.002 || w2 < -0.002) continue;
        height[r * RES + col] = w0 * av + w1 * bv + w2 * cv;
      }
    }
    tris++;
  }
}
console.log('rasterised %d triangles', tris);

// ── The out-of-bounds ring ──────────────────────────────────────────────────
//
// Everything the TIN did not cover. Rather than invent terrain, take the
// elevation at the nearest covered sample and carry it outward, then drift it
// toward a backdrop: ocean stays at sea level and sinks slightly, land climbs
// into barren back-country hills. The join is continuous because the first ring
// of generated samples is, by construction, the edge value itself.

const capC0 = Math.round(toCol(mnX));
const capC1 = Math.round(toCol(mxX));
const capR0 = Math.round(toRow(mnZ));
const capR1 = Math.round(toRow(mxZ));
console.log('capture occupies raster cols %d..%d, rows %d..%d', capC0, capC1, capR0, capR1);

function hash2(i, j) {
  let n = Math.imul(i | 0, 2654435761) ^ Math.imul(j | 0, 40503);
  n = Math.imul(n ^ (n >>> 13), 1274126177);
  return ((n ^ (n >>> 16)) >>> 0) / 4294967296;
}
function noise2(x, y, freq) {
  const fx = x * freq; const fy = y * freq;
  const ix = Math.floor(fx); const iy = Math.floor(fy);
  const tx = fx - ix; const ty = fy - iy;
  const sx = tx * tx * (3 - 2 * tx); const sy = ty * ty * (3 - 2 * ty);
  const a = hash2(ix, iy); const b = hash2(ix + 1, iy);
  const c = hash2(ix, iy + 1); const d = hash2(ix + 1, iy + 1);
  return (a + (b - a) * sx) + ((c + (d - c) * sx) - (a + (b - a) * sx)) * sy;
}

// Close the pinholes the triangle rasteriser leaves along the capture's own
// border first. Without this the ring reads its edge value from an uncovered
// sample, falls back to zero and decides the ground there is sea — which is
// what turned the entire inland east side of the map into ocean, and put
// straight streaks wherever a covered and an uncovered edge sample alternated.
let holes = 0;
for (let pass = 0; pass < 6; pass++) {
  const fixes = [];
  for (let r = capR0; r <= capR1; r++) {
    for (let c = capC0; c <= capC1; c++) {
      if (!Number.isNaN(height[r * RES + c])) continue;
      let sum = 0; let n = 0;
      for (let dr = -1; dr <= 1; dr++) {
        for (let dc = -1; dc <= 1; dc++) {
          const rr = r + dr; const cc = c + dc;
          if (rr < 0 || cc < 0 || rr >= RES || cc >= RES) continue;
          const v = height[rr * RES + cc];
          if (!Number.isNaN(v)) { sum += v; n++; }
        }
      }
      if (n) fixes.push([r * RES + c, sum / n]);
    }
  }
  if (!fixes.length) break;
  for (const [i, v] of fixes) height[i] = v;
  holes += fixes.length;
}
if (holes) console.log('closed %d pinholes inside the capture', holes);

// Anything still unfilled inside the capture is a real hole, not a pinhole, and
// the ring fill below will quietly patch it with a border elevation — a plateau
// or a pit in the middle of the city, indistinguishable in the log from the
// 83 km2 of ring that fill is actually for. Count them separately.
let interiorHoles = 0;
for (let r = capR0; r <= capR1; r++) {
  for (let c = capC0; c <= capC1; c++) {
    if (Number.isNaN(height[r * RES + c])) interiorHoles++;
  }
}
if (interiorHoles) {
  console.warn('%d samples inside the capture are STILL unfilled after six '
    + 'passes (%s km2). The ring fill will give them a border elevation, which '
    + 'is wrong for an interior hole.', interiorHoles,
    ((interiorHoles * mPerSample * mPerSample) / 1e6).toFixed(3));
} else {
  console.log('no unfilled samples inside the capture');
}

/**
 * The capture's border elevation, smoothed along the border.
 *
 * Extruding the raw border outward gives every column the value of its one
 * border pixel and carries it straight to the frame edge, so adjacent columns
 * that differ by a few metres of real terrain become hard parallel stripes for
 * two kilometres. Blurring the profile along the border first removes the
 * stripes without moving the join: the ring still starts at the capture's own
 * elevation, it just starts at a locally averaged one.
 */
function smoothProfile(vals, radius) {
  const n = vals.length;
  const out = new Float32Array(n);
  let acc = 0;
  const win = [];
  for (let i = 0; i < n + radius; i++) {
    if (i < n) { win.push(vals[i]); acc += vals[i]; }
    if (win.length > radius * 2 + 1) acc -= win.shift();
    if (i >= radius) out[i - radius] = acc / win.length;
  }
  return out;
}

const PROFILE_BLUR = 90;      // samples, about 380 m at this resolution
const rowAt = (r, c) => {
  const v = height[r * RES + c];
  return Number.isNaN(v) ? 0 : v;
};
const topProf = smoothProfile(
  Float32Array.from({ length: capC1 - capC0 + 1 }, (_, i) => rowAt(capR0, capC0 + i)), PROFILE_BLUR);
const botProf = smoothProfile(
  Float32Array.from({ length: capC1 - capC0 + 1 }, (_, i) => rowAt(capR1, capC0 + i)), PROFILE_BLUR);
const lefProf = smoothProfile(
  Float32Array.from({ length: capR1 - capR0 + 1 }, (_, i) => rowAt(capR0 + i, capC0)), PROFILE_BLUR);
const rigProf = smoothProfile(
  Float32Array.from({ length: capR1 - capR0 + 1 }, (_, i) => rowAt(capR0 + i, capC1)), PROFILE_BLUR);

function edgeAt(c, r) {
  const sc = Math.min(capC1, Math.max(capC0, c));
  const sr = Math.min(capR1, Math.max(capR0, r));
  if (r < capR0 && c >= capC0 && c <= capC1) return topProf[c - capC0];
  if (r > capR1 && c >= capC0 && c <= capC1) return botProf[c - capC0];
  if (c < capC0 && r >= capR0 && r <= capR1) return lefProf[r - capR0];
  if (c > capC1 && r >= capR0 && r <= capR1) return rigProf[r - capR0];
  // A corner: average the two profiles that meet there.
  const a = r < capR0 ? topProf[sc - capC0] : botProf[sc - capC0];
  const b = c < capC0 ? lefProf[sr - capR0] : rigProf[sr - capR0];
  return (a + b) / 2;
}

let filled = 0;
for (let r = 0; r < RES; r++) {
  for (let c = 0; c < RES; c++) {
    if (!Number.isNaN(height[r * RES + c])) continue;
    const sc = Math.min(capC1, Math.max(capC0, c));
    const sr = Math.min(capR1, Math.max(capR0, r));
    const edge = edgeAt(c, r);

    const dM = Math.hypot(c - sc, r - sr) * mPerSample;
    const t = Math.min(1, dM / RING_M);
    const ease = t * t * (3 - 2 * t);

    // Noise in metres and domain-warped, so the ring reads as landform rather
    // than as the blocky lattice a cell-indexed sample gives at this scale.
    const xm = c * mPerSample; const ym = r * mPerSample;
    const warp = (noise2(xm + 9000, ym, 1 / 2600) - 0.5) * 900;
    const ridge = noise2(xm + warp, ym + warp, 1 / 1700);
    const mid = noise2(xm, ym, 1 / 620) - 0.5;
    const fine = noise2(xm, ym, 1 / 190) - 0.5;

    // The far field forgets the edge completely. Holding on to it is the other
    // half of what made stripes: a value that never decays is a value that
    // gets carried to the boundary of the map.
    const backdrop = edge <= 1.2
      ? -18 + fine * 2.5
      : 70 + ridge * 165 + mid * 38 + fine * 12;

    height[r * RES + c] = edge * (1 - ease) + backdrop * ease;
    filled++;
  }
}

let lo = Infinity; let hi = -Infinity;
for (const v of height) { if (v < lo) lo = v; if (v > hi) hi = v; }
console.log('elevation %s .. %s m', lo.toFixed(2), hi.toFixed(2));

// ── Encode ──────────────────────────────────────────────────────────────────
// Round the stored range outward so the numbers in the recipe stay tidy.
const RANGE_LO = Math.floor(lo / 10) * 10;
const RANGE_HI = Math.ceil(hi / 10) * 10;
const span = RANGE_HI - RANGE_LO;

const samples = new Uint16Array(RES * RES);
for (let i = 0; i < height.length; i++) {
  const t = (height[i] - RANGE_LO) / span;
  samples[i] = Math.max(0, Math.min(65535, Math.round(t * 65535)));
}

const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();
const crc32 = (b) => {
  let c = 0xffffffff;
  for (let i = 0; i < b.length; i++) c = CRC[(c ^ b[i]) & 0xff] ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
};
const chunk = (type, data) => {
  const len = Buffer.alloc(4); len.writeUInt32BE(data.length, 0);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4); crc.writeUInt32BE(crc32(body), 0);
  return Buffer.concat([len, body, crc]);
};

const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(RES, 0); ihdr.writeUInt32BE(RES, 4);
ihdr[8] = 16;     // bit depth
ihdr[9] = 0;      // greyscale
const raw = Buffer.alloc(RES * (1 + RES * 2));
for (let r = 0; r < RES; r++) {
  const o = r * (1 + RES * 2);
  raw[o] = 0;
  for (let c = 0; c < RES; c++) {
    const v = samples[r * RES + c];
    raw[o + 1 + c * 2] = v >> 8;          // PNG is big-endian
    raw[o + 2 + c * 2] = v & 0xff;
  }
}
const png = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
  chunk('IHDR', ihdr),
  chunk('IDAT', deflateSync(raw, { level: 6 })),
  chunk('IEND', Buffer.alloc(0)),
]);
writeFileSync(join(OUT, 'sandiego.png'), png);

const r16 = Buffer.alloc(RES * RES * 2);
for (let i = 0; i < samples.length; i++) r16.writeUInt16LE(samples[i], i * 2);
writeFileSync(join(OUT, 'sandiego.r16'), r16);

// One unit of landscape Z scale spans 512 m of the 16-bit range.
const scaleXY = (frame / (RES - 1)) * 100;
const scaleZ = (span * 100) / 512;
const midMetres = RANGE_LO + (32768 / 65535) * span;

const sidecar = {
  source: src,
  producedBy: 'tools/maps3d-terrain.mjs',
  resolution: RES, width: RES, height: RES, bpp: 16,
  frameMetres: { width: frame, height: frame },
  playableMetres: { width: playW, height: playH },
  outOfBoundsRingMetres: RING_M,
  centre: { lat: lat0, lon: lon0 },
  mercatorToGround: K,
  heightRangeMetres: { min: RANGE_LO, max: RANGE_HI },
  observedMetres: { min: +lo.toFixed(2), max: +hi.toFixed(2) },
  unrealLandscapeScale: { x: +scaleXY.toFixed(3), y: +scaleXY.toFixed(3), z: +scaleZ.toFixed(3) },
  unrealLandscapeZOffsetUU: +(midMetres * 100).toFixed(1),
  note: 'Import sandiego.png. Horizontal axes of the source capture are Web '
    + 'Mercator metres; every figure here is already converted to true ground '
    + 'metres by cos(lat). The playable area is the capture, centred; the ring '
    + 'outside it is generated out-of-bounds terrain.',
};
writeFileSync(sidecarJson, JSON.stringify(sidecar, null, 2));

console.log('\nwrote %s  (%s MB)', join(OUT, 'sandiego.png'),
  (png.length / 1048576).toFixed(1));
console.log('wrote %s  (%s MB)', join(OUT, 'sandiego.r16'),
  (r16.length / 1048576).toFixed(1));
console.log('wrote %s', sidecarJson);
console.log('\n--- import recipe ---');
console.log('  resolution     %d x %d', RES, RES);
console.log('  scale          X %s  Y %s  Z %s',
  scaleXY.toFixed(3), scaleXY.toFixed(3), scaleZ.toFixed(3));
console.log('  location       0, 0, %s', (midMetres * 100).toFixed(0));
console.log('  span           %s km square', (frame / 1000).toFixed(2));
console.log('  playable       %s x %s km, centred',
  (playW / 1000).toFixed(2), (playH / 1000).toFixed(2));
